// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 17 May 2017 17:04:46 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "pocketsphinx.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

