// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 02 Sep 2016 20:19:24 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "pocketsphinx.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

