// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 02 Sep 2016 17:34:13 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package pocketsphinx

/*
#cgo pkg-config: pocketsphinx
#include "pocketsphinx.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// NgramInvalidWid as defined in sphinxbase/ngram_model.h:84
	NgramInvalidWid = -1
)

// FeErrorE as declared in sphinxbase/fe.h:254
type FeErrorE int32

// FeErrorE enumeration from sphinxbase/fe.h:254
const (
	FeSuccess              = iota
	FeOutputFileSuccess    = 0
	FeControlFileError     = -1
	FeStartError           = -2
	FeUnknownSingleOrBatch = -3
	FeInputFileOpenError   = -4
	FeInputFileReadError   = -5
	FeMemAllocError        = -6
	FeOutputFileWriteError = -7
	FeOutputFileOpenError  = -8
	FeZeroEnergyError      = -9
	FeInvalidParamError    = -10
)

// NgramFileType as declared in sphinxbase/ngram_model.h:82
type NgramFileType int32

// NgramFileType enumeration from sphinxbase/ngram_model.h:82
const (
	NgramInvalid NgramFileType = -1
	NgramAuto    NgramFileType = 0
	NgramArpa    NgramFileType = 1
	NgramDmp     NgramFileType = 2
	NgramDmp32   NgramFileType = 3
)

// NgramCase as declared in sphinxbase/ngram_model.h:187
type NgramCase int32

// NgramCase enumeration from sphinxbase/ngram_model.h:187
const (
	NgramUpper NgramCase = iota
	NgramLower NgramCase = 1
)
