// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 28 Aug 2017 14:20:45 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

package pocketsphinx

/*
#cgo pkg-config: pocketsphinx
#include "pocketsphinx.h"
#include "jsgf.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// ArgRequired as defined in sphinxbase/cmd_ln.h:102
	ArgRequired = 1
	// ArgInteger as defined in sphinxbase/cmd_ln.h:106
	ArgInteger = 2
	// ArgFloating as defined in sphinxbase/cmd_ln.h:110
	ArgFloating = 4
	// ArgString as defined in sphinxbase/cmd_ln.h:114
	ArgString = 8
	// ArgBoolean as defined in sphinxbase/cmd_ln.h:118
	ArgBoolean = 16
	// ArgStringList as defined in sphinxbase/cmd_ln.h:122
	ArgStringList = 32
	// ArgInt32 as defined in sphinxbase/cmd_ln.h:144
	ArgInt32 = 2
	// ArgFloat32 as defined in sphinxbase/cmd_ln.h:148
	ArgFloat32 = 4
	// ArgFloat64 as defined in sphinxbase/cmd_ln.h:152
	ArgFloat64 = 4
	// ArgMax as defined in sys/syslimits.h:75
	ArgMax = 262144
	// NgramInvalidWid as defined in sphinxbase/ngram_model.h:83
	NgramInvalidWid = -1
)

// FeErrorE as declared in sphinxbase/fe.h:292
type FeErrorE int32

// FeErrorE enumeration from sphinxbase/fe.h:292
const (
	FeSuccess              = iota
	FeOutputFileSuccess    = 0
	FeControlFileError     = -1
	FeStartError           = -2
	FeUnknownSingleOrBatch = -3
	FeInputFileOpenError   = -4
	FeInputFileReadError   = -5
	FeMemAllocError        = -6
	FeOutputFileWriteError = -7
	FeOutputFileOpenError  = -8
	FeZeroEnergyError      = -9
	FeInvalidParamError    = -10
)

// NgramFileType as declared in sphinxbase/ngram_model.h:81
type NgramFileType int32

// NgramFileType enumeration from sphinxbase/ngram_model.h:81
const (
	NgramInvalid NgramFileType = -1
	NgramAuto    NgramFileType = 0
	NgramArpa    NgramFileType = 1
	NgramBin     NgramFileType = 2
)

// NgramCase as declared in sphinxbase/ngram_model.h:166
type NgramCase int32

// NgramCase enumeration from sphinxbase/ngram_model.h:166
const (
	NgramUpper NgramCase = iota
	NgramLower NgramCase = 1
)
