// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 02 Sep 2016 17:31:25 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package pocketsphinx

/*
#cgo pkg-config: pocketsphinx
#include "pocketsphinx.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// FeErrorE as declared in sphinxbase/fe.h:254
type FeErrorE int32

// FeErrorE enumeration from sphinxbase/fe.h:254
const ()

// NgramFileType as declared in sphinxbase/ngram_model.h:82
type NgramFileType int32

// NgramFileType enumeration from sphinxbase/ngram_model.h:82
const ()

// NgramCase as declared in sphinxbase/ngram_model.h:187
type NgramCase int32

// NgramCase enumeration from sphinxbase/ngram_model.h:187
const ()
