// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 03 Sep 2016 19:39:55 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

/*
Package pocketsphinx provides Go bindings for libpocketsphinx, a lightweight speech recognition engine.
*/
package pocketsphinx
