// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Sep 2017 19:47:43 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package pocketsphinx provides Go bindings for libpocketsphinx, a lightweight speech recognition engine.
*/
package pocketsphinx
