// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 02 Sep 2016 17:34:13 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package pocketsphinx

/*
#cgo pkg-config: pocketsphinx
#include "pocketsphinx.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Decoder as declared in pocketsphinx/pocketsphinx.h:68
type Decoder C.ps_decoder_t

// Nbest as declared in pocketsphinx/pocketsphinx.h:73
type Nbest C.ps_nbest_t

// Seg as declared in pocketsphinx/pocketsphinx.h:78
type Seg C.ps_seg_t

// File as declared in include/stdio.h:153
type File C.FILE

// Arg as declared in sphinxbase/cmd_ln.h:93
type Arg struct {
	Name           string
	Type           int32
	Deflt          string
	Doc            string
	ref8495e8ec    *C.arg_t
	allocs8495e8ec interface{}
}

// CommandLn as declared in sphinxbase/cmd_ln.h:179
type CommandLn C.cmd_ln_t

// Anytype as declared in sphinxbase/prim_type.h:112
const sizeofAnytype = unsafe.Sizeof(C.anytype_t{})

type Anytype [sizeofAnytype]byte

// Logmath as declared in sphinxbase/logmath.h:108
type Logmath C.logmath_t

// Fe as declared in sphinxbase/fe.h:249
type Fe C.fe_t

// NgramModel as declared in sphinxbase/ngram_model.h:66
type NgramModel C.ngram_model_t

// NgramClass as declared in sphinxbase/ngram_model.h:71
type NgramClass C.ngram_class_t

// NgramIter as declared in sphinxbase/ngram_model.h:369
type NgramIter C.ngram_iter_t

// NgramModelSetIter as declared in sphinxbase/ngram_model.h:566
type NgramModelSetIter C.ngram_model_set_iter_t

// Lattice as declared in pocketsphinx/ps_lattice.h:55
type Lattice C.ps_lattice_t

// Latnode as declared in pocketsphinx/ps_lattice.h:63
type Latnode C.ps_latnode_t

// LatnodeIter as declared in pocketsphinx/ps_lattice.h:68
type LatnodeIter C.ps_latnode_iter_t

// Latlink as declared in pocketsphinx/ps_lattice.h:76
type Latlink C.ps_latlink_t

// LatlinkIter as declared in pocketsphinx/ps_lattice.h:81
type LatlinkIter C.ps_latlink_iter_t

// Mllr as declared in pocketsphinx/ps_mllr.h:55
type Mllr C.ps_mllr_t

// FsgSet as declared in pocketsphinx/fsg_set.h:59
type FsgSet C.fsg_set_t

// FsgSetIter as declared in pocketsphinx/fsg_set.h:64
type FsgSetIter struct {
	Idx            uint
	refb26723b3    *C.hash_iter_t
	allocsb26723b3 interface{}
}

// FsgLink as declared in sphinxbase/fsg_model.h:71
type FsgLink struct {
	FromState      int32
	ToState        int32
	Logs2prob      int32
	Wid            int32
	refe7ca59ff    *C.fsg_link_t
	allocse7ca59ff interface{}
}

// FsgModel as declared in sphinxbase/fsg_model.h:107
type FsgModel struct {
	Refcount       int32
	Name           []byte
	NWord          int32
	NWordAlloc     int32
	Vocab          [][]byte
	Silwords       []uint32
	Altwords       []uint32
	Lmath          []Logmath
	NState         int32
	StartState     int32
	FinalState     int32
	Lw             float32
	ref22935ee7    *C.fsg_model_t
	allocs22935ee7 interface{}
}

// FsgArciter as declared in sphinxbase/fsg_model.h:122
type FsgArciter C.fsg_arciter_t
